### ISSUE TITLE
default behavior of copy_hisafe_template not logical? (overwriting any template)

### ISSUE THREAD

**Issue by mariegosme** [kevinwolz/hisafer#119]
by default, overwrite is true (which I think is dangerous), even when new.name is provided, which does not make sense in my opinion: if a new name is provided, a new folder should be created alongside any existing folders. On Christian's computer, using copy_hisafe_template with a new name lead to erasing the "agroforestry" folder that Christian had created in his working directory.

**Comment by kevinwolz** [comment]
Good point! I will fix this now.
