### ISSUE TITLE
hard-coded installation path

### ISSUE THREAD

**Issue by mariegosme** [kevinwolz/hisafer#128]
note from a user (see solution at the end): 
after running:
> devtools::install_github("kevinwolz/hisafer")
There is a long response in the end of which I got an error message:
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'
* removing 'C:/Users/houska/Documents/R/R-3.6.0/library/hisafer'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/houska/AppData/Local/Temp/RtmpcTqRL9/file308018b82f53/hisafer_1.4.14.tar.gz’ had non-zero exit status

Solution:
devtools::install_github("kevinwolz/hisafer", INSTALL_opts='--no-staged-install')

**Comment by kevinwolz** [comment]
I'm glad the solution worked, but I wish we knew why the standard approach is failing. This same issue has happened for others as well.

**Comment by kevinwolz** [comment]
@mariegosme, I just made some updates that might help with this. Can you try installing hisafer onto your computer from Github (after all my recent bug fixes, you'll want the latest version anyway - 1.4.19)? On my computer, it works just fine with no additional arguments.

devtools::install_github("kevinwolz/hisafer")

@Guillaume-Blanchet maybe you can try to do this as well? It would be great if one of you could test on Windows as well.

**Comment by mariegosme** [comment]
it works! thanks

**Comment by assaron** [comment]
@kevinwolz Do you remember what was the culprit? I have this problem with my own package, and can't figure where this problem is coming from. The error message is not very helpful.
