### ISSUE TITLE
hi-sAFe crashes with current poplar.tree file

### ISSUE THREAD

**Issue by mariegosme** [kevinwolz/hisafer#136]
Message from Jens Hansen: In the poplar.tree-file that comes in the template template_common, several parameter names have not yet been renamed following the latest Hi-sAFe version (examples: fineRootLifespan and fineRootAnoxiaLifespan in walnut-hybrid are rootHalfLife and rootAnoxiaHalfLIfe respectively, in the poplar file). This causes simulations to crash at the day of tree planting. I made a fixed poplar file with all the parameter values of the original poplar file, but with the right parameter names, which is attached.

[poplar.TXT](https://github.com/kevinwolz/hisafer/files/4103494/poplar.TXT)
Is it possible to replace the poplar.tree file in the common template with this new file?
Thanks

**Comment by kevinwolz** [comment]
Thanks for reporting this! I never use the poplar file, so I clearly forgot to make these updates. Sorry.
