### ISSUE TITLE
minimum value for parameter paramShape1 (root initialization at tree planting)

### ISSUE THREAD

**Issue by mariegosme** [kevinwolz/hisafer#137]
Message from Jens Hansen: In the file that explains all the parameters of the model (Hi-sAFe_v3-1_Parameter_Details-WOLZ.xlsx), on the .pld sheet, paramShape1 has min = 0. However, simulations crash at the day of tree planting, when paramShape1 is set lower than 0.3, which must be the real minimum, corresponding to a root zone radius of 30 cm. I don't know if this minimum is set at 0.3 on purpose, or if it is a mistake, but in the study I am simulating, poplar cuttings with no root are used as planting material, and it would be more realistic to be able to set paramShape1 = 0.01 for example.

**Comment by mariegosme** [comment]
I think this is more a Hi-sAFe than hisafer issue. I forward it anyway just so that future users with the same issue can find the solution (use paramShape1>0.3).
By the way, this parameter from the .pld file is not referenced in hip_params()

**Comment by kevinwolz** [comment]
See response on Hi-sAFe thread.

**Comment by mariegosme** [comment]
For people without access to Hi-safe github, Kevin's answer in a nutshell: "There is no absolute minimum value that this parameter can be. However, whatever shape is created using the paramShape1 parameters needs to overlap with the gravity center of at least one voxel. My guess is that the voxel depth is large in his simulation, and so the initiation root sphere is not even hitting its gravity center, so no roots are getting initialized and the simulation crashes. "
