### ISSUE TITLE
plot_hisafe_scene() Error for cellWidth > 1 

### ISSUE THREAD

**Issue by ThomasGendron** [kevinwolz/hisafer#148]
Hello , 

I noticed some mistake with 'plot_hisafe_scene' when cellWidth > 1. 

I used "restincliere_agroforestry_A2" as template. 

Scene without modification : 

![image](https://user-images.githubusercontent.com/63015958/89989094-b9d6ad00-dc80-11ea-8928-88c10eed5e61.png)

treeCropDistance = TCD = 2 m 
![image](https://user-images.githubusercontent.com/63015958/89989108-c0652480-dc80-11ea-92f5-fb5025049223.png)

No problem here, even for treeCropRadius

But with cellWidth (CW) = 2 m and TCD = 0.5 m, the scene is not correctly describe. 

![image](https://user-images.githubusercontent.com/63015958/89989126-c955f600-dc80-11ea-95e5-1042d646be74.png)

Other test : 
![image](https://user-images.githubusercontent.com/63015958/89990055-19818800-dc82-11ea-97cc-f8710aff071d.png)
![image](https://user-images.githubusercontent.com/63015958/89990061-1be3e200-dc82-11ea-8464-5a8efa855017.png)

This issues don't come from hisafe, we check it on the output and the intercrop is well assigned. 

Hypothesis : 
- The unite use to calculate intercrop border position is not the meter but meter(TCD)*cellWitdh. 
- The origin use to calculate maincrop distance is not the tree but a other point. 

Thanks and good luck

**Comment by kevinwolz** [comment]
Thanks for finding this! The fix will be available soon in hisafer 1.5.0. There are several other updates happening as a result of the upgrade to Hi-sAFe 4.1.
