### ISSUE TITLE
DOS vs UNIX line breaks Error

### ISSUE THREAD

**Issue by FrancescoReyes** [kevinwolz/hisafer#80]
When using build_cluster_script( ) to produce .sh files to be used on the cluster on Windows, 
I get a DOS vs UNIX line breaks Error.

![dos vs unix line breaks error](https://user-images.githubusercontent.com/33550518/38315760-6dead77a-3829-11e8-8881-96e192460901.jpg)

**Comment by kevinwolz** [comment]
Fixed in version 0.1.9
